#!/usr/bin/env ruby

require 'awesome_print'

def log_path( logit, path )
  return if ! logit

  require 'awesome_print'
  ap path
  puts "=" * 40
end


def remove_system_bins( path )
  path.delete_if { |p| p == '/usr/bin' || p == '/bin' }
end


logit         = false
home          = ENV['HOME']
java_home     = ENV['JAVA_HOME']
javafx_home   = ENV['JAVAFX_HOME']
groovy_home   = ENV['GROOVY_HOME']
gradle_home   = ENV['GRADLE_HOME']
ant_home      = ENV['ANT_HOME']
local         = '/usr/local'
misc          = "#{home}/misc"

# $X11/bin
# $HOST_PATH
# $OS_PATH

if ARGV[0] == 'logit'
  logit = true
end


path = <<-EOS
  #{java_home}/bin
  #{javafx_home}/bin
  #{ant_home}/bin
  #{home}/bin
  #{groovy_home}/bin
  #{gradle_home}/bin
  /usr/local/pgsql/bin
  /etc
  #{local}/bin
  #{local}/sbin
  #{local}/kde/bin
  .
EOS

path    = path.split( "\n" ).map{ |l| l.strip }
source  = ENV['PATH'].split ":"
#source  = []


path.each do |item|
  next if source.include? item
  next if item.nil? || item.empty?

  source << item
end

source = remove_system_bins( source )
source << '/bin/'
source << '/usr/bin/'
source << '/sbin/'
source << '/usr/sbin/'
source << "#{misc}/'Sublime Text 2'"
log_path logit, source


# puts "=" * 40
# p source

puts source.join ":"

